apiVersion: v1
kind: BuildConfig
metadata:
  name: creativeben.Charlie-python-api.development
  labels:
    app: Charlie-python-api
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/creativeben/Charlie-python-api.git'
      ref: development
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: charlie-dev
        - name: BRANCH
          value: development
